sudo: required
services:
  - docker
before_install:
  - docker build -t tfawibe/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tfawibe/react-test npm test -- --coverage

after_success:
  - docker build -t tfawibe/multi-client ./client
  - docker build -t tfawibe/multi-nginx  ./nginx
  - docker build -t tfawibe/multi-server ./server
  - docker build -t tfawibe/multi-worker ./worker
  #log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tfawibe/multi-client
  - docker push tfawibe/multi-nginx
  - docker push tfawibe/multi-server
  - docker push tfawibe/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-482443200100"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
