sudo: required
services:
  - docker
before_install:
  - docker build -t tfawibe/react-test -f ./client/Dockerfile.dev .client

script:
  - docker run tfawibe/react-test npm test -- --coverage

after_success:
  - docker build -t tfawibe/multi-client -f ./client
  - docker build -t tfawibe/multi-nginx -f ./nginx
  - docker build -t tfawibe/multi-server -f ./server
  - docker build -t tfawibe/multi-worker -f ./worker
  #log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tfawibe/multi-client
  - docker push tfawibe/multi-nginx
  - docker push tfawibe/multi-server
  - docker push tfawibe/multi-worker
